// Generated by ReScript, PLEASE EDIT WITH CARE


let Stream = {};

let Fs = {
  Stream: Stream
};

let Path = {};

let URL = {};

let ChildProcess = {};

export {
  Fs,
  Path,
  URL,
  ChildProcess,
}
/* No side effect */
